name: publish
on:
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    name: publish
    runs-on: windows-latest
    steps:
        - name: Publish Module to PowerShell Gallery
          uses: pcgeek86/publish-powershell-module-action@v20
          id: publish-module
          with:
           NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
