name: publish
on:
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    name: publish
    runs-on: windows-latest
    steps:
        - name: Publish PowerShell
          uses: natescherer/publish-powershell-action@v1.0.3
          with:
            token: ${{ secrets.PSGALLERY_KEY }}
            target: gallery
            path: .\Module\UUPDumpDownloader.psd1
