name: publish

on:
    workflow_dispatch:
jobs:
   publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish
        env:
            PSGALLERY_KEY: ${{ secrets.PSGALLERY_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path .\Module -NuGetApiKey $env:PSGALLERY_KEY -Verbose
          $parameters = @{
          Name        = "UUPDumpDownloader"
          NuGetApiKey = $PSGALLERY_KEY
          LicenseUri  = "https://raw.githubusercontent.com/innovatodev/UUPDumpDownloader/main/LICENSE"
          Tag         = 'Windows', 'ISO', 'UUP'
          ReleaseNote = 'https://raw.githubusercontent.com/innovatodev/UUPDumpDownloader/main/CHANGELOG.md'
          }
          Publish-Module @parameters
